<?php
use \Framework\Tools\Helper\RoutesHelper;
use \Tools\Helper\UserHelper;
?>

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>dev&m||e</title>
	<link rel="stylesheet" type="text/css" href="../Assets/css/style.css"> 	
	<script type="text/javascript" src="../Assets/js/jquery/jquery-3.3.1.min.js"></script>
	<script type="text/javascript" src="../Assets/js/jquery/jquery-migrate-1.4.1.min.js"></script>
	<script src="../Assets/js/module/nav.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Roboto:400,700" rel="stylesheet">
</head>
<body>
	<header class="l-header header">
		<nav class="nav">
			<a class="nav__logo" href="<?= RoutesHelper::Path("DisplayHome"); ?>">dev&m||e</a>
			<span class="nav__burger">
				<i class="fas fa-bars"></i>
			</span>
		</nav>
		<section id="nav__overlay" class="nav__overlay">
			<section class="nav__overlay__content">
				<ul>
					<li><a href="<?= RoutesHelper::Path("DisplayHome"); ?>">Accueil</a></li>
					<?php 
					if (UserHelper::IsLogin())
					{
					?>
					<li>Administration<!--
						--><ul>
							<li><a href="<?= RoutesHelper::Path("ManageImage"); ?>">Images</a></li><!--
							--><li><a href="<?= RoutesHelper::Path("ManageCategory"); ?>">Catégories</a></li><!--
							--><li><a href="<?= RoutesHelper::Path("ManagePost"); ?>">Articles</a></li>
						</ul>
					</li><!--
					--><?php } ?><!--
					--><li>Catégories</li><!--
					--><li><a href="<?= RoutesHelper::Path("DisplayContact"); ?>">Contact</a></li><!--
					--><li><a href="<?= RoutesHelper::Path("DisplayAbout"); ?>">A propos</a></li>
				</ul>
			</section>
			<div class="nav__overlay__close">
				<i class="fas fa-times"></i>
			</div>
		</section>
	</header>
	<main class="l-main main">
		<?php
			if (isset($this->content))
			{
				include($this->content);
			} 
		?>
	</main>
	<footer class="l-footer footer">
		<span class="footer__login">
			<?php
			if (!UserHelper::IsLogin())
			{
			?>
			<a href="<?= RoutesHelper::Path("LoginUser"); ?>">
				<i class="fas fa-sign-in-alt"></i>
			</a>
			<?php 
			} 
			else 
			{
			?>
			<a href="<?= RoutesHelper::Path("LogoutUser"); ?>">
				<i class="fas fa-sign-out-alt"></i>
			</a>
			<?php } ?>
		</span>
		<p class="footer__copyright">
			Jérôme Guillevic © Copyright 2018
		</p>
	</footer>
</body>
</html>