<?php
use \Framework\Tools\Helper\RoutesHelper;

$posts = $params["posts"];
?>

<script src="../Assets/js/module/carousel.js"></script>
<script id="dsq-count-scr" src="//devnmore.disqus.com/count.js" async></script>

<section class="carousel">
	<ul>
<?php
foreach ($posts as $post) 
{
?>
   		<li class="carousel__item">
			<a href="<?= RoutesHelper::Path("DisplayPost", [ "slug" => $post->GetSlug() ]); ?>">
   				<img class="carousel__item__image" src="<?= $post->GetImage()->GetRelativePath(); ?>">
   				<section class="carousel__item__info">
   					<div class="carousel__item__info__title"><?= $post->GetTitle(); ?></div>
   					<div class="carousel__item__info__description">
   						<p><?= $post->GetDescription(); ?></p>
    				</div>
				</section>
			</a>
    	</li>
<?php
}
?>
	</ul>
	<button class="carousel__button carousel__button--previous"><i class="fas fa-chevron-left"></i></button>
	<button class="carousel__button carousel__button--next"><i class="fas fa-chevron-right"></i></button>
</section>

<section class="l-content content">
<?php
$index = 0;

foreach ($posts as $post) 
{
	if ($index === 0)
	{
?>
	<article class="thumbnail-post">
  		<header class="thumbnail-post__miniature">
  			<a href="<?= RoutesHelper::Path("DisplayPost", [ "slug" => $post->GetSlug() ]); ?>">
				<img src="<?= $post->GetImage()->GetRelativePath(); ?>">
			</a>
		</header>
		<section class="thumbnail-post__info">
			<div class="thumbnail-post__info__title">
				<a href="<?= RoutesHelper::Path("DisplayPost", [ "slug" => $post->GetSlug() ]); ?>">
					<h2><?= $post->GetTitle(); ?></h2>
				</a>
			</div>
			<div class="thumbnail-post__info__description">
				<p><?= $post->GetDescription(); ?></p>
			</div>
			<div class="thumbnail-post__info__footer">
				<a class="thumbnail-post__info__footer__category" href=""><?= $post->GetCategory()->GetName(); ?></a>
				<a class="thumbnail-post__info__footer__comments-count" href="<?= RoutesHelper::Path("DisplayPost", [ "slug" => $post->GetSlug()."#disqus_thread" ]); ?>">Lien</a>
			</div>
		</section>
	</article>

<?php
	}
	else
	{
?>				
	<article class="thumbnail-small-post">
  		<header class="thumbnail-small-post__miniature">
  			<a href="<?= RoutesHelper::Path("DisplayPost", [ "slug" => $post->GetSlug() ]); ?>">
				<img src="<?= $post->GetImage()->GetRelativePath(); ?>">
			</a>
		</header>
		<section class="thumbnail-small-post__info">
			<div class="thumbnail-small-post__info__title">
				<a href="<?= RoutesHelper::Path("DisplayPost", [ "slug" => $post->GetSlug() ]); ?>">
					<h2><?= $post->GetTitle(); ?></h2>
				</a>
			</div>
			<div class="thumbnail-small-post__info__footer">
				<a class="thumbnail-small-post__info__footer__category" href=""><?= $post->GetCategory()->GetName(); ?></a>
				<a class="thumbnail-small-post__info__footer__comments-count" href="<?= RoutesHelper::Path("DisplayPost", [ "slug" => $post->GetSlug() ])."#disqus_thread"; ?>"></a>
			</div>
		</section>
	</article>
<?php
	}
	$index++;
}
?>
</section>