<?php
$category = $params["category"];
?>

<form class="form" action="<?= $_SERVER['REQUEST_URI'] ?>" method="POST">
	<h1>Éditer une catégorie</h1>
	<input type="hidden" id="category-id" name="category-id" value="<?= $category->GetId(); ?>">
	<section>
		<label for="category-name">Nom</label>
		<input type="text" id="category-name" name="category-name" value="<?= $category->GetName(); ?>" maxlength="35">
	</section>
	<section>
		<label for="category-color">Couleur</label>
		<input type="color" id="category-color" name="category-color" value="<?= $category->GetColor(); ?>">
	</section>
	<section>
		<label for="category-is-visible">Visible ?</label>
		<input type="checkbox" id="category-is-visible" name="category-is-visible" <?php if ($category->GetIsVIsible()) { echo "checked"; } ?>>
	</section>
	<section class="form__buttons">
		<ul>
			<li>
				<button class="button" type="submit" id="category-save">Enregistrer</button>
			</li><!--
			--><li>
				<button class="button--danger" type="reset" id="category-reset">Réinitialiser</button>
			</li>
		</ul>
	</section>
</form>