<section class="l-content content">
	<article>
		<header>
			<h1>A propos</h1>
		</header>
		<section>
			<ul>
				<li>Qu'est-ce qu'on y trouve sur ton blog ?</li>
				<p>Déjà bonjour à toi !<br/>
				Qu'est ce qu'on peut y trouver sur ce blog ? Bonne question !<br/>
				Principalement des articles sur tout ce qui tourne autour du codage.<br/>
				Mais si l'humeur m'en prend, peut être des articles sur le bricolage :)</p>
				<li>Ca me sert à quoi ?</li>
				<p>Encore une bonne question, je commence à bien t'aimer toi !<br/>
				A passer le temps mais surtout à t'éviter de chercher pendant des jours une solution à un problème.<br/>
				Et ça, c'est une bonne chose !</p>
				<li>Et d'abord, t'es qui toi ?</li>
				<p>Merci de demander !<br/>
				Je suis juste un humble développeur qui un jour s'est décidé à faire un site pour tester ses compétences et partager des astuces.</p>
				<li>J'aime bien ce que tu fais, je fais comment pour te complimenter ?</li>
				<p>Tu te souviens du bouton sur lequel tu as cliqué pour arriver ici ?<br/>
				Eh bah c'est celui juste à sa droite.<br/>
				Mais vu que je suis gentil, voilà un raccourci : <a href="/contact">Contact</a>.</p>
			</ul>
		</section>
	</article>
</section>