<script src="../Assets/js/module/disqus.js"></script>

<?php
$post = $params["post"];

setlocale(LC_TIME, 'fr_FR.utf8','fra');
?>
			
<section class="l-content content">
	<article class="post">
		<header class="post__header">
			<img class="post__header__img" src="<?= $post->GetImage()->GetRelativePath(); ?>">
			<h1 class="post__header__title"><?= $post->GetTitle(); ?></h1>
			<section class="post__header__description">
				<p><?= $post->GetDescription(); ?></p>
			</section>
			<section class="post__header__complement">
				<p>
					<span><?= strftime("%e %B %G, %H:%M:%S", date_create($post->GetCreationDate())->getTimestamp()); ?></span>
				</p>
			</section>
		</header>
		<section class="post__content">
			<?= $post->GetContent(); ?>
		</section>
		<footer>
			<div id="disqus_thread"></div>
		</footer>
	</article>
</section>