<script src="../Assets/js/module/image-form.js"></script>

<?php
$image = $params["image"];
if (array_key_exists("mode", $params))
{
	$mode = $params["mode"];
}
if (array_key_exists("source", $params))
{
	$source = $params["source"];
}
 
if (!isset($mode) || ($mode !== "ADD" && $mode !== "UPDATE") || ($mode === "ADD" && !isset($source)) || (isset($source) && $source !== "LOCAL" && $source !== "URL"))
{
?>
<section>
	<p>Cas non géré.</p>
</section>
<?php	
}
else
{
?>
<form class="form" action="<?= $_SERVER['REQUEST_URI'] ?>" method="POST" enctype="multipart/form-data">
	<h1><?php if ($mode === "ADD") { echo "Ajouter"; } else { echo "Mettre à jour"; } ?> une image</h1>
	<input type="hidden" id="source" name="source" value="<?= $source; ?>">
<?php
	if ($mode === "ADD")
	{
		if ($source === "LOCAL")
		{
?>
	<section>
		<label for="image-local-chooser">Sélectionnez un fichier</label>
		<input type="file" accept="image/*" id="image-local-chooser" name="image-local-chooser">
	</section>
<?php
		}
		else if ($source === "URL")
		{
?>
	<section>
		<label for="image-url">Url</label>
		<input type="text" id="image-url" name="image-url">
	</section>
<?php
		}
?>
	<section>
		Aperçu
		<img id="image-preview" src="">
	</section>
<?php
	}
?>
	<input type="hidden" id="image-id" name="image-id" value="<?= $image->GetId(); ?>">
	<input type="hidden" id="image-path" name="image-path" value="<?= $image->GetPath(); ?>">
	<section>
		<label for="image-name">Nom</label>
		<input type="text" id="image-name" name="image-name" value="<?= $image->GetName(); ?>" maxlength="35">
	</section>
	<section>
		<label for="image-extension">Extension</label>
		<input type="text" id="image-extension" name="image-extension" value="<?= $image->GetExtension(); ?>" maxlength="10">
	</section>
	<section>
		<label for="image-is-visible">Visible ?</label>
		<input type="checkbox" id="image-is-visible" name="image-is-visible" <?php if ($image->GetIsVIsible()) { echo "checked"; } ?>>
	</section>
	<section class="form__buttons">
		<ul>
			<li>
				<button class="button" type="submit" id="image-save">Enregistrer</button>
			</li><!--
			--><li>
				<button class="button--danger" type="reset" id="image-reset">Réinitialiser</button>
			</li>
		</ul>
	</section>
</form>
<?php
}
?>